apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    project: {{ .Values.project }}
spec:
  secretName: {{ .Release.Name }}-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: {{ .Values.host }}
  acme:
    config:
    - http01:
        ingress: {{ .Release.Name }}
      domains:
      - {{ .Values.host }}
